spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: my-secret-pw
        url: jdbc:mysql://localhost:3306/userdb
        username: root
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        generate-ddl: true
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                format_sql: true
        show-sql: true
    mail:
      host: localhost
      port: 1025
      username: hello
      password: hello

      properties:
        mail:
          smtp:
            ssl:
              trust: "*"
            auth: true
            starttls:
              enable: true
            connectiontimeout: 5000
            timeout: 3000
            writetimeout: 5000
